import { z } from 'zod/v4'
import { customZod } from '../../../libraries/custom-zod-types'

export type ServerConfigType = {
    AllowedOrigins: string[] | string;
    Host: string;
    Port: number;
    KeyAlgorithm: string;
    PublicKeyDirectory: string;
    PrivateKeyDirectory: string;
}

export default {
    AllowedOrigins: {
        name: 'ALLOWED_ORIGINS',
        description: 'allowed origins for cors',
        default: {
            _: 'localhost,127.0.0.1',
        },
        validator: z.preprocess((val: string|undefined) =>  val?.split(','), z.array(z.string()).default([])),
    },
    Host: {
        name: 'HOSTNAME',
        description: 'Who to listen to',
        default: {
            _: 'localhost',
            production: '0.0.0.0',
        },
        validator: z.string(),
    },
    Port: {
        name: 'PORT',
        description: 'Port to run the server',
        default: {
            _: 3000,
            production: 8080,
        },
        validator: customZod.application.port,
    },
    KeyAlgorithm: {
        name: 'PRIVATE_KEY_ALGORITHM',
        description: 'algorithm to use for private key',
        default: {
            _: 'RSA-OAEP-256',
        },
        validator: z.string(),
    },
    PrivateKeyDirectory: {
        name: 'PRIVATE_KEY_URL',
        description: 'Path to private key',
        default: {
            _: './keys/jwtRS256.private.pem', // Default if generated by the script.
        },
        validator: z.string(),
    },
    PublicKeyDirectory: {
        name: 'PUBLIC_KEY_URL',
        description: 'Path to private key',
        default: {
            _: './keys/jwtRS256.public.pem', // Default if generated by the script.
        },
        validator: z.string(),
    }
}
