import { z } from 'zod/v4'
import { customZod } from '../../../libraries/custom-zod-types'

export type ServerConfigType = {
    Host: string,
    Port: number
    PrivateKeyAlgorithm: string;
    PrivateKeyURL: string;
}

export default {
    Host: {
        name: 'HOSTNAME',
        description: 'Who to listen to',
        default: {
            _: '127.0.0.1',
            production: '0.0.0.0',
        },
        validator: z.ipv4(),
    },
    Port: {
        name: 'PORT',
        description: 'Port to run the server',
        default: {
            _: 3000,
            production: 8080,
        },
        validator: customZod.application.port,
    },
    PrivateKeyAlgorithm: {
        name: 'PRIVATE_KEY_ALGORITHM',
        description: 'algorithm to use for private key',
        default: {
            _: 'RS256',
        },
        validator: z.string(),
    },
    PrivateKeyURL: {
        name: 'PRIVATE_KEY_URL',
        description: 'Path to private key',
        default: {
            _: './keys/jwtRS256.private.pem', // Default if generated by the script.
        },
        validator: z.ipv4(),
    },
}
